### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Alex7692** [cScotPlay/Primal-Skies#37]
**Problem**
Game continuously crashing after clicking the Play Button of the launcher with the default version of forge for this modpack. 
**Details**
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by cScotPlay** [comment]
Interesting.  Do you have more of the crash report available?

**Comment by Alex7692** [comment]
The problem is now solved after installing the older version of java (8.0) on the computer, but still, thanks for your reply : ) Really enjoying this modpack right now.
